# Generated by Django 5.2.7 on 2025-11-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('item', models.CharField(max_length=199, primary_key=True, serialize=False)),
                ('quant', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
            options={
                'db_table': 'material',
            },
        ),
    ]
