# Generated by Django 5.2.7 on 2025-10-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_festa_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='situacao',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('desativado', 'Desativado')], default='ativo', max_length=15),
        ),
    ]
